apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deployment.name}}
  labels:
    name: {{.Values.deployment.name}}
spec:
  replicas: {{default "1" .Values.deployment.replicas  }}
  selector:
    matchLabels:
      name: {{.Values.deployment.name}}
  template:
    metadata:
      labels:
        name: {{.Values.deployment.name}}
    spec:
      containers:
      - name: {{.Values.deployment.name}}
        image: {{.Values.deployment.image}}
        resources:
          requests:
            memory: {{ .Values.deployment.resources.requests.memory }}
            cpu: {{ .Values.deployment.resources.requests.cpu }}
          limits:
            memory: {{ .Values.deployment.resources.limits.memory }}
            cpu: {{ .Values.deployment.resources.limits.cpu }}
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "20"]
        env:
        - name: "ASPNETCORE_ENVIRONMENT" 
          value: {{.Values.deployment.env}}
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 60
          httpGet:
            scheme: HTTP
            path: /
            port: 80
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 60
          httpGet:
            scheme: HTTP
            path: /
            port: 80 


